# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTEST_RERUNS: 1
  PYTEST_RERUN_DELAY: 2
  CF_FM_API_ENDPOINT: https://api.apps1-fm-htz.icloud.intel.com
  CF_AZ_API_ENDPOINT: https://api.apps1-az-htz.icloud.intel.com
  CF_ORG: "Server_Tools"
  APIGEE_PRE_PROD_TOKEN_URL: https://apis-dev.intel.com/v1/auth/token
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: This is test build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: servertools

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Define Prod variables
        if: github.ref == 'refs/heads/main'
        run: |-
          echo "TOKEN_URL=$APIGEE_PRE_PROD_TOKEN_URL" >> $GITHUB_ENV
          echo "API_APP_CLIENT_ID=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
          echo "FWTRACK_DB_CS=${{ vars.API_URL }}" >> $GITHUB_ENV
          echo "CUPBUILDER_ENVIRONMENT=PROD" >> $GITHUB_ENV
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
